### ISSUE TITLE
Insert Failed

### ISSUE THREAD

**Issue by oghenez** [pimbrouwers/Sequel#4]
This insert 
```
var sqlBuilder = new SqlBuilder()
  .Insert("dbo.Test")
  .Columns("Name", "Salary")
  .Values("'John'", "50").Values("'Jane'", "100");
```
failed with the following error

> BC30456	'Columns' is not a member of 'SqlBuilder'.

**Comment by tokmendoza** [comment]
Use ".Into" instead of ".Columns"

**Comment by tokmendoza** [comment]
> This insert
> 
> ```
> var sqlBuilder = new SqlBuilder()
>   .Insert("dbo.Test")
>   .Columns("Name", "Salary")
>   .Values("'John'", "50").Values("'Jane'", "100");
> ```
> 
> failed with the following error
> 
> > BC30456	'Columns' is not a member of 'SqlBuilder'.

Use ".Into" instead of ".Columns"

**Comment by pimbrouwers** [comment]
@tokmendoza Thank you!
